added readme file
codurance/site-hubspot-migration pull request #1
Opened 2020-10-21 17:19 UTC by nicolasbelfis

2020-10-21 17:48 UTC, ewansheldon requested changes
generally good job man - the instructions were really easy to follow as i set up my sandbox

2020-10-21 17:48 UTC, ewansheldon commented on README.md
> +2. create a merge request to the `stage branch`
wouldn't this be less confusing if this was called `staging`

also i think only the `branchname` should be in code block like:

2. create a merge request to the `staging` branch

2020-10-21 17:48 UTC, ewansheldon commented on README.md
> +Once the changes has been accepted create a merge request to `master branch`
`master` branch?

2020-10-21 17:48 UTC, ewansheldon commented on README.md
> +6. check the file hubspot.config.yml has been created
maybe put `hubspot.config.yml` in code block (but i'm not sure about that - that's just my preference)

2020-10-22 08:14 UTC, Morinslash reviewed
I think it would be good to mention also that files removed from the repo are not removed from the HubSpot Accounts and they have to be removed manually inside porta

Adding links to documentation also will be good (CLI commands etc)

2020-10-22 08:23 UTC, nicolasbelfis commented on README.md
> +6. check the file hubspot.config.yml has been created
not sure either, if the file is created it is done by the hs process. But maybe we can later one point people to the doc that explains that file ?

2020-10-22 08:55 UTC, ewansheldon approved these changes
looks good to me now

2020-10-22 09:03 UTC, Morinslash approved these changes

2020-10-22 09:40 UTC, merged