Lp clients block
codurance/site-hubspot-migration pull request #148
Opened 2021-06-04 15:12 UTC by stefi23

2021-06-09 16:15 UTC, RodrigoCastroS commented on version_control/Codurance_September2020/modules/LP-clients-block.module/module.html
> +    <p class="lp-partners-clients-container__cta">
I don't know if I would wrap a CTA in a p tag. Maybe a div?

2021-06-09 16:17 UTC, RodrigoCastroS requested changes
I left you a comment related to a tag

2021-06-10 07:44 UTC, stefi23 commented on version_control/Codurance_September2020/modules/LP-clients-block.module/module.html
> +    <p class="lp-partners-clients-container__cta">
I changed it to a div tag. I was thinking to put an a tag but then it will style it maybe as a link.

2021-06-10 15:03 UTC, RodrigoCastroS approved these changes
All good

2021-06-10 15:14 UTC, merged