Feature/events page gated content
codurance/site-hubspot-migration pull request #202
Opened 2022-04-05 10:23 UTC by RodrigoCastroS

In order to differentiate from gated to ungated content we changed a bit the style of the cards also the section has changed accordingly

2022-04-05 11:55 UTC, vicarali requested changes
I just left a single comment on a part that maybe could be improved (I'm not entirely sure, but please review it before the merge). Other than that, I already tested it on staging and everything looks perfect!

2022-04-05 11:55 UTC, vicarali commented on version_control/Codurance_September2020/modules/Recent-Events-Listing.module/module.html
> +          {% if event.video is string_containing 'livestorm' %}
I don't know if it would be better to set these different "classnames" and "text" values as variables (along with the condition). This way the "button_primary" snippet call would only be required to be included once. What do you think?

2022-04-06 11:29 UTC, RodrigoCastroS commented on version_control/Codurance_September2020/modules/Recent-Events-Listing.module/module.html
> +          {% if event.video is string_containing 'livestorm' %}
I've created a small object to contain the info, so it's a bit cleaner when passing the parameters to the button mactro

2022-04-06 12:08 UTC, vicarali approved these changes
Re-checked on staging and everything looks perfect! Thank you!

2022-04-06 13:59 UTC, merged