Translate sign up message to pt
codurance/site-hubspot-migration pull request #348
Opened 2023-04-05 12:05 UTC by tfbica

2023-04-05 12:20 UTC, RodrigoCastroS approved these changes
LGTM 👍🏼

2023-04-12 13:50 UTC, RodrigoCastroS commented on version_control/Codurance_September2020/templates/blog-post.html
> +          {% if locale == 'es' %}
Probably the same applying the same approach mentioned on line 115 could be beneficial for readability purposes also

2023-04-12 13:57 UTC, RodrigoCastroS commented on version_control/Codurance_September2020/templates/partials/header-insights-blog-pt.html
I think we've talked about this implementation on a meeting yesterday @tfbica, so it might be better to check and have this feature on the body on the blogs listing. I believe you didn't have time to check this.

2023-04-12 14:17 UTC, RodrigoCastroS commented on version_control/Codurance_September2020/templates/partials/header-insights-blog-pt.html
After reviewing this, I believe you won't need this one. You can translate the copy with the current partial we are using at the moment.

2023-04-12 14:32 UTC, RodrigoCastroS commented on version_control/Codurance_September2020/templates/partials/header.html
Currently the language switcher is not working properly when the PT language is active. It might be related to line 43 of this file.

2023-04-12 14:32 UTC, vicarali commented on version_control/Codurance_September2020/templates/blog-index-pt.html
> +        <div class="custom-blog-listing__intro">
Hello! We just recovered this message from the ES blog listing page that was pointing to the EN listing. Please add the PT copy that you would like to have here

2023-04-12 14:33 UTC, RodrigoCastroS requested changes
Hi, I left some comments on the code to review. Let @vicarali or me if you have any doubts.

2023-04-14 09:19 UTC, tfbica commented on version_control/Codurance_September2020/templates/partials/header-insights-blog-pt.html
Ok, I'll delete it

2023-04-14 09:22 UTC, tfbica commented on version_control/Codurance_September2020/templates/partials/header.html
Yes it was missing checking also if not pt.

2023-04-14 09:22 UTC, tfbica commented on version_control/Codurance_September2020/templates/blog-index-pt.html
> +        <div class="custom-blog-listing__intro">
Done, thanks

2023-04-17 10:21 UTC, RodrigoCastroS approved these changes
I had a look and it seems its working on my end. Great job!

2023-04-17 10:38 UTC, merged